#!/usr/bin/env python3
"""Generate Rust data tables (STX kernels + DIP weights) from dav2d C sources.

Mechanical bit-exact transcription, like cdf_gen.py. Inner dims are flattened so
each kernel/weight block passes straight to the ported algorithm:
  STX 4x4  [14][3][8][16]  -> [[[i8; 128]; 3]; 14]      (8*16 flattened)
  STX 8x8  [11][3][32][48] -> [[[i8; 1536]; 3]; 11]     (32*48 flattened)
  DIP      [6][64][11]     -> [[[u16; 11]; 64]; 6]

Usage: gen_tables.py <dav2d_src_dir> <out.rs>
"""
import re
import sys


def extract_values(text, name):
    """Return the flat list of ints in `name[...] = { ... };`."""
    m = re.search(re.escape(name) + r'\b[^=]*=\s*', text)
    if not m:
        raise SystemExit(f"array {name} not found")
    start = text.index('{', m.end())
    depth, i = 0, start
    while i < len(text):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                break
        i += 1
    body = text[start:i + 1]
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    body = re.sub(r'//.*', '', body)
    return [int(n) for n in re.findall(r'-?\d+', body)]


def reshape(vals, dims):
    expected = 1
    for d in dims:
        expected *= d
    assert len(vals) == expected, f"got {len(vals)} values, expected {expected} for {dims}"
    # reshape to dims, but keep the last `flatten_to` dims flat (handled by caller)
    return vals


def emit_3d(name, rust_ty, vals, outer, mid, inner):
    """Emit a `[[[ty; inner]; mid]; outer]` static from flat `vals`."""
    assert len(vals) == outer * mid * inner
    lines = [f"pub static {name}: [[[{rust_ty}; {inner}]; {mid}]; {outer}] = ["]
    idx = 0
    for o in range(outer):
        lines.append("    [")
        for _m in range(mid):
            chunk = vals[idx:idx + inner]
            idx += inner
            # wrap long inner arrays
            s = ", ".join(str(v) for v in chunk)
            lines.append(f"        [{s}],")
        lines.append("    ],")
    lines.append("];")
    return "\n".join(lines)


# RectTxfmSize order → scan name (from dav2d_scans in scan.c). 64-wide reuses 32.
SCAN_INDEX = [
    "4x4", "8x8", "16x16", "32x32", "32x32",                 # TX_4X4..TX_64X64
    "4x8", "8x4", "8x16", "16x8", "16x32", "32x16", "32x32", "32x32",  # RTX_4X8..RTX_64X32
    "4x16", "16x4", "8x32", "32x8", "16x32", "32x16",        # RTX_4X16..RTX_64X16
    "4x32", "32x4", "8x32", "32x8", "4x32", "32x4",          # RTX_4X32..RTX_64X4
]


def emit_scans(scan_src):
    """Parse every `scan_WxH[]` array from scan.c and emit Rust statics + index."""
    scans = {}
    for m in re.finditer(r'scan_(\w+)\[\][^=]*=\s*\{([^}]*)\}', scan_src):
        name, body = m.group(1), m.group(2)
        scans[name] = [int(n) for n in re.findall(r'\d+', body)]
    lines = []
    for name in sorted(set(SCAN_INDEX)):
        vals = scans[name]
        # validate: each scan is a permutation of 0..len-1
        assert sorted(vals) == list(range(len(vals))), f"scan_{name} not a permutation"
        s = ", ".join(str(v) for v in vals)
        lines.append(f"static SCAN_{name.upper()}: [u16; {len(vals)}] = [{s}];")
    refs = ", ".join(f"&SCAN_{n.upper()}" for n in SCAN_INDEX)
    lines.append(f"\n/// Coefficient scan order per RectTxfmSize (dav2d `dav2d_scans`).")
    lines.append(f"pub static SCANS: [&[u16]; {len(SCAN_INDEX)}] = [{refs}];")
    return "\n".join(lines), len(scans)


def main():
    src, out = sys.argv[1], sys.argv[2]
    with open(f"{src}/stx_tables.c") as f:
        stx = f.read()
    with open(f"{src}/dip_tables.c") as f:
        dip = f.read()
    with open(f"{src}/scan.c") as f:
        scan_src = f.read()

    k44 = extract_values(stx, "dav2d_stx_4x4_kernel")   # [14][3][8][16]
    k88 = extract_values(stx, "dav2d_stx_8x8_kernel")   # [11][3][32][48]
    dipw = extract_values(dip, "dav2d_dip_weights")     # [6][64][11]

    reshape(k44, [14, 3, 8, 16])
    reshape(k88, [11, 3, 32, 48])
    reshape(dipw, [6, 64, 11])

    parts = [
        "//! GENERATED by tools/gen_tables.py from dav2d stx_tables.c / dip_tables.c.",
        "//! STX secondary-transform basis kernels + DIP prediction weights.",
        "//! Inner dims flattened so each block passes straight to the ported kernels.",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        "",
        emit_3d("STX_4X4_KERNEL", "i8", k44, 14, 3, 8 * 16),
        "",
        emit_3d("STX_8X8_KERNEL", "i8", k88, 11, 3, 32 * 48),
        "",
        emit_3d("DIP_WEIGHTS", "u16", dipw, 6, 64, 11),
        "",
    ]
    scans_rs, n_scans = emit_scans(scan_src)
    parts.append(scans_rs)
    parts.append("")
    with open(out, "w") as f:
        f.write("\n".join(parts))

    # cross-checks (first values, hand-verified against the C source)
    assert k44[:4] == [102, -53, -5, -2], k44[:4]
    print(f"OK  STX44={len(k44)}  STX88={len(k88)}  DIP={len(dipw)}  scans={n_scans}  -> {out}")


if __name__ == "__main__":
    main()
